name: latest iPad Add Sheet (Fastlane)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for secrets (optional)"
        required: false
        default: "prod"

jobs:
  fastlane_add:
    runs-on: macos-14
    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install gems
        run: |
          set -e
          bundle install --path vendor/bundle || gem install fastlane -N

      - name: Run Fastlane (add sheet only)
        run: |
          set -e
          if command -v bundle >/dev/null && bundle exec fastlane --version >/dev/null 2>&1; then
            bundle exec fastlane ipad_screenshots project:"NotesApp.xcodeproj" scheme:"NotesApp" xcode:"15.2" shots:"add"
          else
            fastlane ipad_screenshots project:"NotesApp.xcodeproj" scheme:"NotesApp" xcode:"15.2" shots:"add"
          fi

      - name: Upload Add sheet screenshots
        uses: actions/upload-artifact@v4
        with:
          name: latest-ipad-add-fastlane
          path: |
            images/ipad13-2064x2752/add.png
            images/ipad13-2048x2732/add.png

