name: iOS App Store Upload v3

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment name for environment-scoped secrets"
        required: false
        default: "prod"

jobs:
  release:
    name: Build, Sign and Upload to App Store Connect
    runs-on: macos-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_API_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
      APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
      APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Show Xcode version
      run: xcodebuild -version

    - name: Prepare App Icons from master (no placeholders)
      run: |
        # Provide a finalized 1024x1024 PNG at branding/app_icon_1024.png or set APP_ICON_MASTER env
        if [ ! -f branding/app_icon_1024.png ] && [ -z "$APP_ICON_MASTER" ]; then
          echo "No master icon provided; generating a default branded icon";
          python3 scripts/make_master_icon.py;
        fi
        APP_ICON_MASTER=${APP_ICON_MASTER:-branding/app_icon_1024.png}
        python3 scripts/prepare_app_icons_from_master.py

    - name: Compute unique build number
      run: |
        NEW_BUILD=$(date +%Y%m%d%H%M)
        echo "NEW_BUILD=$NEW_BUILD" >> $GITHUB_ENV
        echo "::notice title=Build Number::CFBundleVersion will be $NEW_BUILD"

    - name: Preflight - Check required secrets presence
      run: |
        check() { if [ -z "$1" ]; then echo "::warning title=Missing secret::${2} not set"; else echo "${2}: present"; fi }
        echo "Environment: ${{ inputs.environment }}"
        check "${BUILD_CERTIFICATE_BASE64}" "BUILD_CERTIFICATE_BASE64"
        check "${P12_PASSWORD}" "P12_PASSWORD"
        check "${KEYCHAIN_PASSWORD}" "KEYCHAIN_PASSWORD"
        check "${BUILD_PROVISION_PROFILE_BASE64}" "BUILD_PROVISION_PROFILE_BASE64"
        if [ -n "${APP_STORE_CONNECT_API_KEY_ID}" ] && [ -n "${APP_STORE_CONNECT_ISSUER_ID}" ] && [ -n "${APP_STORE_CONNECT_API_PRIVATE_KEY}" ]; then
          echo "App Store Connect API secrets: present (will upload to TestFlight via API key)"
        elif [ -n "${APP_STORE_CONNECT_USERNAME}" ] && [ -n "${APP_SPECIFIC_PASSWORD}" ]; then
          echo "Apple ID upload secrets present (will upload to TestFlight via Apple ID)"
        else
          echo "::notice title=TestFlight upload::No upload credentials set; will skip App Store Connect upload and only produce IPA artifact"
        fi
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_API_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
        APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
        APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}

    - name: Install Apple Certificate
      run: |
        if [ -z "$BUILD_CERTIFICATE_BASE64" ]; then echo "BUILD_CERTIFICATE_BASE64 not set"; exit 1; fi
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

    - name: Install Provisioning Profile
      run: |
        if [ -z "$BUILD_PROVISION_PROFILE_BASE64" ]; then echo "BUILD_PROVISION_PROFILE_BASE64 not set"; exit 1; fi
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
        echo "PP_PATH=$PP_PATH" >> $GITHUB_ENV
        # Extract profile metadata
        security cms -D -i $PP_PATH > $RUNNER_TEMP/profile.plist
        PP_UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' $RUNNER_TEMP/profile.plist)
        PP_NAME=$(/usr/libexec/PlistBuddy -c 'Print :Name' $RUNNER_TEMP/profile.plist)
        echo "Using Provisioning Profile: $PP_NAME ($PP_UUID)"
        echo "PP_UUID=$PP_UUID" >> $GITHUB_ENV
        echo "PP_NAME=$PP_NAME" >> $GITHUB_ENV

    - name: Build and Archive (Release - unsigned)
      run: |
        xcodebuild archive \
          -project NotesApp.xcodeproj \
          -scheme NotesApp \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath ${{ runner.temp }}/CodeSnake-Release.xcarchive \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
          CURRENT_PROJECT_VERSION=$NEW_BUILD

    - name: Extract App Metadata (version/build/bundle)
      run: |
        APP_DIR=$(ls -d ${{ runner.temp }}/CodeSnake-Release.xcarchive/Products/Applications/*.app | head -n 1)
        PLIST="$APP_DIR/Info.plist"
        if [ ! -f "$PLIST" ]; then echo "::error title=Info.plist not found::$PLIST"; exit 1; fi
        APP_VERSION=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$PLIST")
        APP_BUILD=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$PLIST")
        BUNDLE_ID=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$PLIST")
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
        echo "APP_BUILD=$APP_BUILD" >> $GITHUB_ENV
        echo "BUNDLE_ID=$BUNDLE_ID" >> $GITHUB_ENV
        echo "::notice title=Build Metadata::BundleID=$BUNDLE_ID Version=$APP_VERSION Build=$APP_BUILD"

    - name: Generate Export Options (manual with profile UUID)
      run: |
        # Derive team ID from profile if not provided
        TEAM_ID=${{ secrets.IOS_TEAM_ID }}
        if [ -z "$TEAM_ID" ]; then
          TEAM_ID=$(/usr/libexec/PlistBuddy -c 'Print :TeamIdentifier:0' $RUNNER_TEMP/profile.plist 2>/dev/null || true)
        fi
        cat > $RUNNER_TEMP/export-options.plist <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
            <key>signingCertificate</key>
            <string>Apple Distribution</string>
            <key>provisioningProfiles</key>
            <dict>
                <key>${BUNDLE_ID}</key>
                <string>${PP_UUID}</string>
            </dict>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>uploadSymbols</key>
            <true/>
        </dict>
        </plist>
        EOF

    - name: Export Signed IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath ${{ runner.temp }}/CodeSnake-Release.xcarchive \
          -exportPath ${{ runner.temp }}/export-release \
          -exportOptionsPlist $RUNNER_TEMP/export-options.plist
        IPA_PATH=$(ls ${{ runner.temp }}/export-release/*.ipa | head -n 1)
        if [ -z "$IPA_PATH" ]; then echo "::error title=Export failed::No IPA produced"; exit 1; fi
        echo "IPA_PATH=$IPA_PATH" >> $GITHUB_ENV
        echo "::notice title=Export Complete::IPA=$(basename "$IPA_PATH") BundleID=$BUNDLE_ID Version=$APP_VERSION Build=$APP_BUILD"

    - name: Upload Signed IPA as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CodeSnake-Release-IPA
        path: ${{ runner.temp }}/export-release/*.ipa
        retention-days: 90

    - name: Prepare App Store Connect API key (optional)
      if: ${{ env.APP_STORE_CONNECT_API_KEY_ID != '' && env.APP_STORE_CONNECT_ISSUER_ID != '' && env.APP_STORE_CONNECT_API_PRIVATE_KEY != '' }}
      env:
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_API_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.appstoreconnect/private_keys
        echo "$APP_STORE_CONNECT_API_PRIVATE_KEY" > ~/.appstoreconnect/private_keys/AuthKey_${APP_STORE_CONNECT_API_KEY_ID}.p8
        chmod 600 ~/.appstoreconnect/private_keys/AuthKey_${APP_STORE_CONNECT_API_KEY_ID}.p8

    - name: Upload to App Store Connect (TestFlight)
      if: ${{ env.APP_STORE_CONNECT_API_KEY_ID != '' && env.APP_STORE_CONNECT_ISSUER_ID != '' && env.APP_STORE_CONNECT_API_PRIVATE_KEY != '' }}
      env:
        API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      run: |
        IPA_PATH=$(ls ${{ runner.temp }}/export-release/*.ipa | head -n 1)
        if [ -z "$IPA_PATH" ]; then echo "No IPA found"; exit 1; fi
        # Upload via altool (API key)
        echo "::group::Uploading to App Store Connect via API key (altool)"
        xcrun altool --upload-app -f "$IPA_PATH" -t ios --apiKey "$API_KEY_ID" --apiIssuer "$ISSUER_ID" --verbose
        EXITCODE=$?
        echo "::endgroup::"
        if [ $EXITCODE -ne 0 ]; then echo "::error title=Upload failed::altool exit $EXITCODE"; exit $EXITCODE; fi
        echo "::notice title=Upload Succeeded::Uploaded BundleID=$BUNDLE_ID Version=$APP_VERSION Build=$APP_BUILD"

    - name: Upload to App Store Connect (Apple ID fallback)
      if: ${{ (env.APP_STORE_CONNECT_API_KEY_ID == '' || env.APP_STORE_CONNECT_ISSUER_ID == '' || env.APP_STORE_CONNECT_API_PRIVATE_KEY == '') && env.APP_STORE_CONNECT_USERNAME != '' && env.APP_SPECIFIC_PASSWORD != '' }}
      env:
        ASC_USERNAME: ${{ env.APP_STORE_CONNECT_USERNAME }}
        ASC_PASSWORD: ${{ env.APP_SPECIFIC_PASSWORD }}
      run: |
        IPA_PATH=$(ls ${{ runner.temp }}/export-release/*.ipa | head -n 1)
        if [ -z "$IPA_PATH" ]; then echo "No IPA found"; exit 1; fi
        # Upload via altool (Apple ID)
        echo "::group::Uploading to App Store Connect via Apple ID (altool)"
        xcrun altool --upload-app -f "$IPA_PATH" -t ios -u "$ASC_USERNAME" -p "$ASC_PASSWORD" --verbose
        EXITCODE=$?
        echo "::endgroup::"
        if [ $EXITCODE -ne 0 ]; then echo "::error title=Upload failed::altool exit $EXITCODE"; exit $EXITCODE; fi
        echo "::notice title=Upload Succeeded::Uploaded BundleID=$BUNDLE_ID Version=$APP_VERSION Build=$APP_BUILD"

    - name: "Post-upload: Verify build in App Store Connect"
      if: ${{ env.APP_STORE_CONNECT_API_KEY_ID != '' && env.APP_STORE_CONNECT_ISSUER_ID != '' && env.APP_STORE_CONNECT_API_PRIVATE_KEY != '' }}
      run: |
        python3 -m pip install --user pyjwt cryptography >/dev/null 2>&1 || true
        python3 scripts/asc_check.py

    - name: Clean up keychain
      if: always()
      run: |
        security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
